sonar.projectKey=task-manager-frontend
sonar.projectName=Task Manager Frontend
sonar.sources=src
sonar.tests=src
sonar.test.inclusions=**/*.spec.ts,**/*.spec.tsx
sonar.exclusions=**/*.spec.ts,**/*.spec.tsx,**/main.tsx,**/test/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8
sonar.qualitygate.wait=true
